### ISSUE TITLE
Failure creating database

### ISSUE THREAD

**Issue by jayvdb** [danielmichaels/RFC.py#7]
I built an RPM with spec at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-RFC.py , and on running `rfc` the first time I get an exception.

```py
[!] Database Not Found! [!]
The database will now be setup...
  [####################################]  100%          
..
[*] Download complete [*]
Download completed in 160.32 seconds
..uncompressing tar.gz...
..Done!
..Beginning database writes..
Traceback (most recent call last):
  File "/usr/bin/rfc", line 11, in <module>
    load_entry_point('RFC.py==2019.9.2', 'console_scripts', 'rfc')()
  File "/usr/lib/python3.7/site-packages/rfcpy/rfc.py", line 41, in main
    read_config()
  File "/usr/lib/python3.7/site-packages/rfcpy/helpers/utils.py", line 179, in read_config
    first_run_update()
  File "/usr/lib/python3.7/site-packages/rfcpy/helpers/utils.py", line 246, in first_run_update
    write_to_db()
  File "/usr/lib/python3.7/site-packages/rfcpy/helpers/utils.py", line 324, in write_to_db
    bookmark=bookmark,
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 5963, in create
    inst.save(force_insert=True)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 6150, in save
    pk = self.insert(**field_dict).execute()
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 1785, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 1856, in execute
    return self._execute(database)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 2571, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 2320, in _execute
    cursor = database.execute(self)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 2952, in execute
    sql, params = ctx.sql(query).query()
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 2546, in __sql__
    self._simple_insert(ctx)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 2420, in _simple_insert
    return self._generate_insert((self._insert,), ctx)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 2518, in _generate_insert
    return ctx.sql(CommaNodeList(all_values))
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 1651, in __sql__
    ctx.sql(self.nodes[n_nodes - 1])
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 1649, in __sql__
    ctx.sql(self.nodes[i])
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 601, in sql
    return obj.__sql__(self)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 1308, in __sql__
    return ctx.value(self.value, self.converter)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 613, in value
    value = converter(value)
  File "/usr/lib64/python3.7/site-packages/peewee.py", line 4260, in db_value
    return value if value is None else self.adapt(value)
ValueError: invalid literal for int() with base 10: '8650.xml'
```

I am using python3-peewee-3.9.5-1.3.x86_64 , which is a bit old.  I'll update that now.

The other possible factor is that rfcpy directory in site-packages is read-only as this is a system package, however the error doesnt suggest that this is the problem.

**Comment by jayvdb** [comment]
Upgrading to peewee 3.11.2 solved the problem for me.
The requirements need a minimum version?

**Comment by danielmichaels** [comment]
See #10 
-----------

Fixes include:
- migrating to `poetry` and updating to more recent versions
- exporting `poetry` to `requirements.txt` to ensure compatibility between use cases.

closing but if anyone has similar issues in the future, reopen or raise a new issue.
